### ISSUE TITLE
Project doesn't use the latest npm scripts and rollup config from sveltejs/template

### ISSUE THREAD

**Issue by ztoben** [sveltejs/svelte-todomvc#15]
The npm scripts and rollup config are not in line with https://github.com/sveltejs/template.

I believe there are also some issues with http-server that cause the program to not be served correctly locally (at least for me). Mainly https://github.com/indexzero/http-server/issues/525.

**Comment by Rich-Harris** [comment]
Switched to using Vite, so I'll close this
